#!/bin/bash

letsencrypt certonly --webroot -w /srv/letsencrypt/htdocs -d srcurl.net -d www.srcurl.net
letsencrypt certonly --webroot -w /srv/letsencrypt/htdocs -d github.srcurl.net
letsencrypt certonly --webroot -w /srv/letsencrypt/htdocs -d bitbucket.srcurl.net
